export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const DELETE_PROFILE = 'DELETE_PROFILE';
export const GET_RECIPES = 'GET_RECIPES';
export const GET_RECIPE = 'GET_RECIPE';
export const SAVE_RECIPE = 'SAVE_RECIPE';
export const UNSAVE_RECIPE = 'UNSAVE_RECIPE';
export const UPDATE_RECIPE = 'UPDATE_RECIPE';
export const CREATE_RECIPE = 'CREATE_RECIPE';
export const DELETE_RECIPE = 'DELETE_RECIPE';

//search recipe, filter recipes, get categories, search category...
export const SORT_RECIPES_TITLE_ASC = 'SORT_RECIPES_TITLE_ASC';
export const SORT_RECIPES_TITLE_DESC = 'SORT_RECIPES_TITLE_DESC';
export const SORT_RECIPES_DATE_ASC = 'SORT_RECIPES_DATE_ASC';
export const SORT_RECIPES_DATE_DESC = 'SORT_RECIPES_DATE_DESC';
export const SORT_RECIPES_SAVES_ASC = 'SORT_RECIPES_SAVES_ASC';
export const SORT_RECIPES_SAVES_DESC = 'SORT_RECIPES_SAVES_DESC';

export const GET_RECIPES_BY_TITLE_KEYWORD = 'GET_RECIPES_BY_TITLE_KEYWORD';
export const GET_RECIPES_BY_INGREDIENT_KEYWORD = 'GET_RECIPES_BY_INGREDIENT_KEYWORD';
export const GET_RECIPES_BY_CATEGORY_KEYWORD = 'GET_RECIPES_BY_CATEGORY_KEYWORD';

export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
